"""cria veredito e feedback

Revision ID: c6c783caa3d9
Revises:
Create Date: 2026-09-22 22:48:40.683830

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c6c783caa3d9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "veredito",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hash_trecho", sa.String(length=64), nullable=False),
        sa.Column("trecho_avaliado", sa.Text(), nullable=False),
        sa.Column("estado_veredito", sa.Text(), nullable=False),
        sa.Column("resposta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_veredito_hash_trecho", "veredito", ["hash_trecho"], unique=False
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("veredito_id", sa.Integer(), nullable=False),
        sa.Column("util", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["veredito_id"],
            ["veredito.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_feedback_veredito_id", "feedback", ["veredito_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_feedback_veredito_id", table_name="feedback")
    op.drop_table("feedback")
    op.drop_index("ix_veredito_hash_trecho", table_name="veredito")
    op.drop_table("veredito")
    # ### end Alembic commands ###
