"""As migrações descrevem o mesmo schema que os modelos declaram.

A partir do momento em que existem migrações, passam a existir duas descrições
do mesmo schema. Nada além deste teste garante que continuem iguais — e a
divergência só apareceria quando alguém subisse o ambiente do zero, semanas
depois de ter sido criada.
"""

import os
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

from src.tests.integration.test_sessao import URL_DO_BANCO, banco_alcancavel

BACKEND_DIR = Path(__file__).resolve().parents[3]

pytestmark = pytest.mark.skipif(
    not os.environ.get("CI") and not banco_alcancavel(),
    reason="Postgres indisponível. Suba com: docker compose up -d db",
)


@pytest.fixture
def configuracao() -> Config:
    config = Config(str(BACKEND_DIR / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_DIR / "migrations"))
    return config


@pytest.fixture
def banco_no_topo(configuracao: Config, monkeypatch: pytest.MonkeyPatch) -> Config:
    """Deixa o banco com todas as migrações aplicadas e devolve ao estado vazio.

    Usa o banco de verdade porque é o schema real que precisa ser comparado; um
    banco de outro dialeto compararia contra o comportamento errado.
    """
    monkeypatch.setenv("DATABASE_URL", URL_DO_BANCO)
    command.upgrade(configuracao, "head")
    yield configuracao
    command.downgrade(configuracao, "base")


def test_a_ida_e_a_volta_funcionam(banco_no_topo: Config) -> None:
    """Desfazer precisa funcionar de verdade, não só ser declarado.

    A fixture já aplica na entrada e desfaz na saída; chegar aqui sem exceção
    significa que o ciclo completo passou.
    """
    command.downgrade(banco_no_topo, "base")
    command.upgrade(banco_no_topo, "head")


def test_os_modelos_e_as_migracoes_nao_divergiram(banco_no_topo: Config) -> None:
    """Falha se alguém alterar um modelo sem gerar a migração correspondente."""
    try:
        command.check(banco_no_topo)
    except AutogenerateDiffsDetected as diferenca:
        pytest.fail(
            "modelos e migrações divergiram — gere a migração que falta:\n"
            f"  alembic revision --autogenerate -m 'descreva a mudança'\n\n{diferenca}"
        )
